### ISSUE TITLE
[Task] 마침내 limit / 양승준

### ISSUE THREAD

**Issue by Tarosism** [codestates/Cafe.in#20]
### **ISSUE**

- Group:  `server`
- Type: `feature`

### **TODO**

- [ ]  limit 또는 lastId 기능을 활용해 클라이언트에 지정 갯수만큼만 데이터를 줄 수 있다.
- [ ]  다대다 include에 limit을 걸 수 있다 (subQuery의 패턴 파악하기)
- [x]  전부 실패. 동적인 값에 대한 대비를 시퀄라이즈 구문 내에서 하지 못했다.

### **Labels**

- Estimated time: `E: 3h`
- Group : `server`
- Urgency: `Middle`
