### ISSUE TITLE
[Task] 라우터 설정과 dislike / 양승준

### ISSUE THREAD

**Issue by Tarosism** [codestates/Cafe.in#23]
### **ISSUE**

- Group: `client`, `server`, `sr`
- Type: `feature`

### **TODO**

- [x]  restful은 모르겠고 클라가 쓸 수 있는 라우터 설정
- [x]  dislike도 똑같이 구현
- [x]  입력된 해시태그의 counts 초기값을 null이 아닌 0으로 설정해주기
- [x]  확정 api, data 타입 깃북에 업로드

### **Labels**

- Estimated time: `E: 3h`
- Group : `client`, `server`
- Urgency: `High`
