### ISSUE TITLE
[Task] distance 나타내기 / 양승준

### ISSUE THREAD

**Issue by Tarosism** [codestates/Cafe.in#32]
### **ISSUE**

- Group: `client`, `server`, `sr`
- Type: `feature`
- Detail: 

### **TODO**

- [x]  좌표를 토대로 location 가져오기
- [x]  해당 location으로 리스트 요청하기 (= select의 value를 location으로 바꾸기)
- [x]  거리 계산은 좌표들로 하는 건가요?

### **Labels**

- Estimated time: `E: 6h`
- Group : `client`, `server`
- Urgency: `High`
