### ISSUE TITLE
[Task] Cafe Info page 구성 / 김윤재

### ISSUE THREAD

**Issue by yunjaekim00** [codestates/Cafe.in#34]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: CafeInfo page 구성하기

### **TODO**

- [x]  Component 4개로 나누기
- [x]  styled component 오타 수정
- [x]  지도 표시 넣기
- [x] 현재 위치 파악 기능 넣기
- [x] 현재 위치를 주소로 변환하기 (Google Maps Geocode)
- [x] Dropdown 메뉴 주석처리
