### ISSUE TITLE
[Task] 배포 스택 연구 / 문기훈

### ISSUE THREAD

**Issue by kihunism** [codestates/Cafe.in#35]
### **ISSUE**

- Group:`server`, `sr`
- Type: `deploy`
- Detail: 최대한 과금 없이 배포하는 방법 알아보기

### **TODO**

- [ ]  AWS 및 다른 배포 서비스 알아보기
- [ ]  현 프로젝트 배포 시 과금 비교해보기
- [ ]  과금이 최대한 없고 기업 및 개인이 사용 많이 하는 배포 스택으로 정하기

### **Estimated time**

> Pick one
> 

### **Labels**

- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
