### ISSUE TITLE
[Task] DB에 api 데이터 입력 및 데모 돌리기 / 양승준

### ISSUE THREAD

**Issue by Tarosism** [codestates/Cafe.in#38]
### **ISSUE**

- Group: `client`, `server`
- Type: `feature`

### **TODO**

- [x]  geolocation 빼고 lat 서울 어디로 지정해서 찐데이터 넣고 돌려보기 
- [x]  posts 테이블 최종본 만들기
- [ ]  지역범위 수정 ('구'인가 '동'인가)
- [x]  geolocation과 맵 마커까지 사용한 완성본 돌려보기
- [ ]  지금의 요청주소는 restful한가?

### **Labels**

- Estimated time: `E: 3h`
- Group : `client`, `server`
- Urgency: `High`
