### ISSUE TITLE
[Task] 리팩토링 마무리 / 양승준

### ISSUE THREAD

**Issue by Tarosism** [codestates/Cafe.in#52]
### **ISSUE**

- Group: `client`, `server`
- Type: `feature`

### **TODO**

- [x]  cafe-list, cafe-list-hash 리팩토링 (해시태그는 신경쓰지 않는다)
- [x]  리팩토링 코드로 demo 돌려보기
- [ ]  (optional) OUATH 준비

### **Labels**

- Estimated time: `E: 3h`
- Group : `client`, `server`
- Urgency: `High`
