### ISSUE TITLE
[Task] Code Refactor / 김윤재

### ISSUE THREAD

**Issue by yunjaekim00** [codestates/Cafe.in#59]
### **ISSUE**

- Group: `client`
- Type: `refactor`
- Detail: refactoring the whole structure

### **TODO**

- [ ]  Modal pop업 창 한 곳에 몰기, reusable modal frame
- [ ]  버튼 클릭 이벤트 처리 한 곳에 몰기
- [ ]  Server에 HTTP request 한 곳에 몰기
