### ISSUE TITLE
[Task] 지도 플로우 파악 & map 띄우기 / 양승준

### ISSUE THREAD

**Issue by Tarosism** [codestates/Cafe.in#9]
### **ISSUE**

- Group: `client`, `server`
- Type: `feature`
- Detail: 

### **TODO**

- [x]  화면에 지도 띄우기 + 지도 데이터 파악해서 기록하기
- [x]  공공 api 이용해서 서버에서 뿌려보기 (postman)
* ~~구글이 아니라면 할 수 있지 않을까?~~
* 구글이어도 할 수 있음!
- [x] 위에 두 개 합쳐서 의도하는 위치 나타내기

### **Labels**

- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
